"""empty message

Revision ID: 0c300d8d0131
Revises: ee2b64102cc7
Create Date: 2020-05-01 15:50:01.905649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c300d8d0131'
down_revision = 'ee2b64102cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'membership_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('membership_status', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
