"""empty message

Revision ID: 2dddcb0f1bba
Revises: 0c300d8d0131
Create Date: 2020-05-01 16:59:11.976958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dddcb0f1bba'
down_revision = '0c300d8d0131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('comments', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'comments')
    # ### end Alembic commands ###
