"""empty message

Revision ID: d5c3b30eaf6f
Revises: 
Create Date: 2020-05-01 11:13:38.141789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c3b30eaf6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('fname', sa.String(length=15), nullable=False),
    sa.Column('lname', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('passowrd', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('price',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('fname', sa.String(length=15), nullable=False),
    sa.Column('lname', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('passowrd', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('driverId', sa.Integer(), nullable=False),
    sa.Column('driverValidity', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('membership_status', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehiclelocation',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=15), nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=False),
    sa.Column('make_company', sa.String(length=15), nullable=False),
    sa.Column('model_year', sa.String(length=4), nullable=True),
    sa.Column('registration_tag', sa.String(length=10), nullable=False),
    sa.Column('current_milegae', sa.Integer(), nullable=True),
    sa.Column('last_service', sa.Date(), nullable=True),
    sa.Column('vehicle_condition', sa.Integer(), nullable=True),
    sa.Column('Location', sa.Integer(), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Location'], ['vehiclelocation.location_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pickupdatetime', sa.DateTime(), nullable=False),
    sa.Column('dropoffdatetime', sa.DateTime(), nullable=False),
    sa.Column('pickup_location', sa.Integer(), nullable=False),
    sa.Column('dropoff_location', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('vehicle')
    op.drop_table('vehiclelocation')
    op.drop_table('user')
    op.drop_table('price')
    op.drop_table('admin')
    # ### end Alembic commands ###
